#!/usr/bin/env python
# coding: utf-8

# In[1]:


from geopy.geocoders import Nominatim


# In[2]:


geolocator = Nominatim(user_agent="myTest")


# In[4]:


location=geolocator.geocode({"postalcode": "41462", "country": "DE"})


# In[5]:


print(location.address)


# In[6]:


print((location.latitude, location.longitude))


# In[12]:


plzs = ["41460", "41461", "41462", "41463"]


# In[13]:


for plz in plzs:
    location=geolocator.geocode({"postalcode": "41462", "country": "DE"})
    print(plz)


# In[ ]:
